before:
  hooks:
    - go generate .
builds:
  - 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - 
    replacements:
      darwin: MacOS
      linux: Linux
      freebsd: FreeBSD
      386: _i386_
      amd64: x86_64
      arm: ARM32_
      arm64: ARM64_
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
